### ISSUE TITLE
Oct2Py leaves open filehandles in IPython

### ISSUE THREAD

**Issue by fergalm** [blink1073/oct2py#86] opened 2016-03-10 22:41 UTC
Oct2Py is simultaneously saving my life and crashing my code :')

I'm running a large batch job and it keeps crashing with the error message of "Too many open files". I've traced the problem to Octave/Oct2Py, and I strongly suspect the issue is with Oct2Py itself. 

Stripping the problem down to its simplest level, I create the following Octave code, stored in testfunc.m
```octave

function testfunc()
    1+1;
end
```

I then write the following Python function
```python
import numpy as np
from oct2py import Oct2Py

def func(arg):
    with Oct2Py() as octave:
        octave.testfunc()
```

On the command line, I execute
``` bash
lsof | grep python | wc '
```

to measure the number of open files I'm using. I create a function to call `func` 100 times
```python
def main():
    x = np.arange(100)
    map(func, x)
```

and call it from a previously opened IPython session. I find the number of files open from Python increases by about 80,000, or about 800 per invocation of Oct2Py. They all disappear when I close the IPython session, but if I'm running a large job, I eventually hit the max number of allowable open files.

**Comment by blink1073** [comment] 2016-03-12 03:03
Hi @fergalm, what OS are you using?  I tried you code on both Python 2.7 and 3.4 on OSX, and here's what I get before and after running the code:

```bash
ssilvester: ~/workspace/oct2py (master) 2
$ lsof | grep python | wc
      64     578    9374

ssilvester: ~/workspace/oct2py (master) 2
$ lsof | grep python | wc
     297    2675   32880
```

So, only about 2 files per octave session.

**Comment by fergalm** [comment] 2016-03-13 23:07
I'm running python 2.7 on kubuntu 14.04. Would the version of ipython help?

**Comment by blink1073** [comment] 2016-03-15 13:32
Okay, confirmed on Ubuntu 14.04:

```bash
ssilvester@ubuntu:~$ lsof | grep python | wc
   1521   14456  238769
ssilvester@ubuntu:~$ lsof | grep python | wc
  32398  322988 3877131
ssilvester@ubuntu:~$ 
```

**Comment by blink1073** [comment] 2016-03-15 13:32
It may be this weekend before I get a chance to dig in.

**Comment by fergalm** [comment] 2016-03-15 16:36
Grand. It's not the sort of bug I'd have any idea how to isolate, but let me know if I can help.

**Comment by blink1073** [comment] 2016-03-19 14:37
Fixed by db660a4, released as 3.5.2.  The problem was the thread in `_Reader()` was kept left open, I couldn't figure out why the thread itself results in a huge number of open files.

**Comment by fergalm** [comment] 2016-03-24 22:29
Finally got a chance to check the fix against my codebase, and the number of open files now looks essentially flat against runtime. Looks like the bug is squashed. Thanks.

**Comment by blink1073** [comment] 2016-03-25 14:31
Great!

**Closed by blink1073** 2016-03-25 14:31 UTC
