### ISSUE TITLE
error octave-cli not found

### ISSUE THREAD

**Issue by kupiqu** [blink1073/oct2py#147] opened 2019-05-03 13:51 UTC
the executable option does not seem to be considered, I always get the following error:

```
Traceback (most recent call last):
  File "pyOct2PyTest.py", line 5, in <module>
    from oct2py import Oct2Py
  File "/home/miniconda/envs/cenv1/lib/python3.7/site-packages/oct2py/__init__.py", line 38, in <module>
    octave = Oct2Py()
  File "/home/miniconda/envs/cenv1/lib/python3.7/site-packages/oct2py/core.py", line 82, in __init__
    self.restart()
  File "/home/miniconda/envs/cenv1/lib/python3.7/site-packages/oct2py/core.py", line 528, in restart
    logger=self.logger)
  File "/home/miniconda/envs/cenv1/lib/python3.7/site-packages/octave_kernel/kernel.py", line 161, in __init__
    self.executable = self._get_executable()
  File "/home/miniconda/envs/cenv1/lib/python3.7/site-packages/octave_kernel/kernel.py", line 440, in _get_executable
    raise OSError('octave-cli not found, please see README')
OSError: octave-cli not found, please see README
```

**Comment by blink1073** [comment] 2019-05-03 14:57
Closing as a duplicate of #148.

**Comment by kupiqu** [comment] 2019-05-03 14:58
Not duplicate

**Comment by kupiqu** [comment] 2019-05-03 15:01
please reopen, this bug is not solved. even if I set the path to octave-cli in oct2py call, the same error occurs...

**Comment by blink1073** [comment] 2019-05-03 15:07
Are you able to run `octave-cli` directly from your terminal?   If so, what is the output?

**Comment by kupiqu** [comment] 2019-05-03 15:16
As I mentioned in issue #148, octave-cli fails whereas octave works. This seems an issue in upstream octave, perhaps while packaging (flatpak). Will check with them.

However, the issue here is different, it's about the executable option of oct2py not being taken into account. I still think this needs fixing...

**Comment by blink1073** [comment] 2019-05-03 15:19
Ah, I see what the issue is here.  The convenience `octave` instance is created before you get a chance to set the `executable` property.  Given that fact, I think the only right answer is to remove the `executable` argument in favor of using PATH or the OCTAVE_EXECUTABLE environment variable.

**Comment by blink1073** [comment] 2019-05-03 15:20
I'll do that and cut a major version number.

**Comment by kupiqu** [comment] 2019-05-03 15:24
I see. That's unfortunate, I liked having the executable option, but if there's no other way...

**Closed** 2019-05-03 15:36 UTC
Labels: needs_info

**Comment by gblabi** [comment] 2020-09-25 16:16
Hi, sorry I don´t get where the executable argument has to be removed. I am having the same issue

**Comment by milind-prajapat** [comment] 2020-12-25 13:23
Hey! Also have the same error. I am on Octave v6.1.0.  octave-cli works fine through cmd. Path to octave-cli is set to PATH, OCTAVE_EXECUTABLE but still it shows the error.
    raise OSError('OCTAVE_EXECUTABLE does not point to an octave-cli file, please see README')
OSError: OCTAVE_EXECUTABLE does not point to an octave-cli file, please see README
