### ISSUE TITLE
print plot to file gives unexpected error

### ISSUE THREAD

**Issue by roel0** [blink1073/oct2py#83] opened 2016-01-07 14:18 UTC
When you do the following:

```
plot(x,y,'r');
print('-dpng', 'filename', '-r250')
```

and execute in octave (gui or client) everything works fine.

But when I try to run the same script in the same environment with oct2py:

```
Traceback (most recent call last):
  File "../../Python/audio_quality_checker.py", line 15, in <module>
    init()
  File "../../Python/audio_quality_checker.py", line 12, in init
    octave.run("../../Python/octave/test2.m")
  File "C:\Python27\lib\site-packages\oct2py\core.py", line 407, in octave_command
    return self._call(name, *args, **kwargs)
  File "C:\Python27\lib\site-packages\oct2py\core.py", line 514, in _call
    data = self.eval(cmd, temp_dir=temp_dir, **eval_kwargs)
  File "C:\Python27\lib\site-packages\oct2py\core.py", line 284, in eval
    post_call=post_call)
  File "C:\Python27\lib\site-packages\oct2py\core.py", line 807, in evaluate
    raise Oct2PyError(msg)
oct2py.utils.Oct2PyError: Oct2Py tried to run:
"""
load c:\users\rposte~1\appdata\local\temp\tmpvs9g6b\writer.mat "A__"
run(A__);

"""
Octave returned:
nth_element: n must be a scalar or a contiguous range

```
My python script:

```
import oct2py

def init():
    octave = oct2py.Oct2Py()
    octave.run("../../Python/octave/test2.m")
```

Additional info:
-gnuplot is used
-oct2py is latest version
-octave is latest version
-windows

**Comment by roel0** [comment] 2016-01-07 14:25
Was apparently already mentioned in #81

**Comment by blink1073** [comment] 2016-01-09 13:37
Yes, I haven't had a chance to test this on a Windows machine.

**Comment by blink1073** [comment] 2016-01-23 15:04
@roel0, I just released 3.5 which should fix this, can you confirm?

**Comment by blink1073** [comment] 2016-01-23 15:08
Closing this one, since it is a duplicate of #81.

**Closed by blink1073** 2016-01-23 15:08 UTC

**Comment by roel0** [comment] 2016-01-25 07:26
I can confirm that version 3.5 resolves the problem!

**Comment by blink1073** [comment] 2016-01-25 14:29
Great, thanks @roel0!
